/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#cbc5c3",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#32302f",
        "secondary-container": "#4b4847",
        "inverse-primary": "#bb152c",
        "on-primary-container": "#5b000e",
        "primary-container": "#ff535b",
        "surface": "#131313",
        "inverse-surface": "#e5e2e1",
        "primary": "#ffb3b1",
        "tertiary-container": "#988f8b",
        "tertiary": "#cfc4c0",
        "secondary-fixed": "#e7e1df",
        "primary-fixed": "#ffdad8",
        "background": "#131313",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed": "#ece0dc",
        "on-background": "#e5e2e1",
        "on-primary-fixed": "#410007",
        "on-tertiary-fixed-variant": "#4d4542",
        "on-surface-variant": "#e4bebc",
        "surface-tint": "#ffb3b1",
        "surface-container": "#201f1f",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "outline-variant": "#5b403f",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#92001c",
        "on-tertiary": "#362f2d",
        "on-secondary-container": "#bcb7b5",
        "on-tertiary-container": "#2f2826",
        "error": "#ffb4ab",
        "inverse-on-surface": "#313030",
        "surface-container-lowest": "#0e0e0e",
        "secondary": "#cbc5c3",
        "outline": "#ab8987",
        "on-secondary-fixed": "#1d1b1a",
        "on-primary": "#680011",
        "tertiary-fixed-dim": "#cfc4c0",
        "primary-fixed-dim": "#ffb3b1",
        "on-tertiary-fixed": "#201a18",
        "surface-variant": "#353534",
        "surface-bright": "#3a3939",
        "on-secondary-fixed-variant": "#494645"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
